# Generated by Django 4.0.4 on 2022-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts_pics'),
        ),
    ]
