# Generated by Django 4.0.4 on 2022-06-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_photos_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Posts',
        ),
    ]
